### ISSUE TITLE
Real-world projects section

### ISSUE THREAD

**Issue by cristim** [SerifAndSemaphore/go-serverless-list#6]
What do you think about adding a list of real-world full-blown serverless projects written in Go? Some people may use it as an example on what kind of stuff people are building with Go.

I am the author of such a [project](https://github.com/cristim/autospotting) and I'd like to have it featured here under such a section.

**Comment by tmaiaroto** [comment]
That sounds great (and, on a side note, your project looks really interesting!). Would you like to add a section, include it, and submit a pull request? Thanks!

**Comment by hom-bahrani** [comment]
I've added a few examples in and updated one of the links, hope thats ok
